CREATE TABLE Monero (
    Date INTEGER NOT NULL,
    Open FLOAT NOT NULL,
    Close FLOAT NOT NULL,
    High FLOAT NOT NULL,
    Low FLOAT NOT NULL,
    Marketcap BIGINT NOT NULL,
	Symbol VARCHAR(10) NOT NULL,
    Name VARCHAR(30) NOT NULL
);

CREATE TABLE Tether (
    Date INTEGER NOT NULL,
    Open FLOAT NOT NULL,
    Close FLOAT NOT NULL,
    High FLOAT NOT NULL,
    Low FLOAT NOT NULL,
    Marketcap BIGINT NOT NULL,
	Symbol VARCHAR(10) NOT NULL,
    Name VARCHAR(30) NOT NULL
);

CREATE TABLE Bitcoin (
    Date INTEGER NOT NULL,
    Open FLOAT NOT NULL,
    Close FLOAT NOT NULL,
    High FLOAT NOT NULL,
    Low FLOAT NOT NULL,
    Marketcap BIGINT NOT NULL,
	Symbol VARCHAR(10) NOT NULL,
    Name VARCHAR(30) NOT NULL
);

CREATE TABLE Dogecoin (
    Date INTEGER NOT NULL,
    Open FLOAT NOT NULL,
    Close FLOAT NOT NULL,
    High FLOAT NOT NULL,
    Low FLOAT NOT NULL,
    Marketcap BIGINT NOT NULL,
	Symbol VARCHAR(10) NOT NULL,
    Name VARCHAR(30) NOT NULL
);

CREATE TABLE BinanceCoin (
    Date INTEGER NOT NULL,
    Open FLOAT NOT NULL,
    Close FLOAT NOT NULL,
    High FLOAT NOT NULL,
    Low FLOAT NOT NULL,
    Marketcap BIGINT NOT NULL,
	Symbol VARCHAR(10) NOT NULL,
    Name VARCHAR(30) NOT NULL
);

CREATE TABLE Ethereum (
    Date INTEGER NOT NULL,
    Open FLOAT NOT NULL,
    Close FLOAT NOT NULL,
    High FLOAT NOT NULL,
    Low FLOAT NOT NULL,
    Marketcap BIGINT NOT NULL,
	Symbol VARCHAR(10) NOT NULL,
    Name VARCHAR(30) NOT NULL
);

CREATE TABLE GDAXI (
    Date INTEGER NOT NULL,
    Open FLOAT NOT NULL,
    Close FLOAT NOT NULL,
    High FLOAT NOT NULL,
    Low FLOAT NOT NULL,
    Marketcap BIGINT NOT NULL,
	Symbol VARCHAR(10) NOT NULL,
    Name VARCHAR(30) NOT NULL
);

CREATE TABLE GSPTSE (
    Date INTEGER NOT NULL,
    Open FLOAT NOT NULL,
    Close FLOAT NOT NULL,
    High FLOAT NOT NULL,
    Low FLOAT NOT NULL,
    Marketcap BIGINT NOT NULL,
	Symbol VARCHAR(10) NOT NULL,
    Name VARCHAR(30) NOT NULL
);

CREATE TABLE HSI (
    Date INTEGER NOT NULL,
    Open FLOAT NOT NULL,
    Close FLOAT NOT NULL,
    High FLOAT NOT NULL,
    Low FLOAT NOT NULL,
    Marketcap BIGINT NOT NULL,
	Symbol VARCHAR(10) NOT NULL,
    Name VARCHAR(30) NOT NULL
);

CREATE TABLE IXIC (
    Date INTEGER NOT NULL,
    Open FLOAT NOT NULL,
    Close FLOAT NOT NULL,
    High FLOAT NOT NULL,
    Low FLOAT NOT NULL,
    Marketcap BIGINT NOT NULL,
	Symbol VARCHAR(10) NOT NULL,
    Name VARCHAR(30) NOT NULL
);

CREATE TABLE J203 (
    Date INTEGER NOT NULL,
    Open FLOAT NOT NULL,
    Close FLOAT NOT NULL,
    High FLOAT NOT NULL,
    Low FLOAT NOT NULL,
    Marketcap BIGINT NOT NULL,
	Symbol VARCHAR(10) NOT NULL,
    Name VARCHAR(30) NOT NULL
);

CREATE TABLE KS11 (
    Date INTEGER NOT NULL,
    Open FLOAT NOT NULL,
    Close FLOAT NOT NULL,
    High FLOAT NOT NULL,
    Low FLOAT NOT NULL,
    Marketcap BIGINT NOT NULL,
	Symbol VARCHAR(10) NOT NULL,
    Name VARCHAR(30) NOT NULL
);

CREATE TABLE N100 (
    Date INTEGER NOT NULL,
    Open FLOAT NOT NULL,
    Close FLOAT NOT NULL,
    High FLOAT NOT NULL,
    Low FLOAT NOT NULL,
    Marketcap BIGINT NOT NULL,
	Symbol VARCHAR(10) NOT NULL,
    Name VARCHAR(30) NOT NULL
);

CREATE TABLE N225 (
    Date INTEGER NOT NULL,
    Open FLOAT NOT NULL,
    Close FLOAT NOT NULL,
    High FLOAT NOT NULL,
    Low FLOAT NOT NULL,
    Marketcap BIGINT NOT NULL,
	Symbol VARCHAR(10) NOT NULL,
    Name VARCHAR(30) NOT NULL
);

CREATE TABLE NSEI (
    Date INTEGER NOT NULL,
    Open FLOAT NOT NULL,
    Close FLOAT NOT NULL,
    High FLOAT NOT NULL,
    Low FLOAT NOT NULL,
    Marketcap BIGINT NOT NULL,
	Symbol VARCHAR(10) NOT NULL,
    Name VARCHAR(30) NOT NULL
);

CREATE TABLE NYA (
    Date INTEGER NOT NULL,
    Open FLOAT NOT NULL,
    Close FLOAT NOT NULL,
    High FLOAT NOT NULL,
    Low FLOAT NOT NULL,
    Marketcap BIGINT NOT NULL,
	Symbol VARCHAR(10) NOT NULL,
    Name VARCHAR(30) NOT NULL
);

CREATE TABLE oneSS (
    Date INTEGER NOT NULL,
    Open FLOAT NOT NULL,
    Close FLOAT NOT NULL,
    High FLOAT NOT NULL,
    Low FLOAT NOT NULL,
    Marketcap BIGINT NOT NULL,
	Symbol VARCHAR(10) NOT NULL,
    Name VARCHAR(30) NOT NULL
);

CREATE TABLE SSMI (
    Date INTEGER NOT NULL,
    Open FLOAT NOT NULL,
    Close FLOAT NOT NULL,
    High FLOAT NOT NULL,
    Low FLOAT NOT NULL,
    Marketcap BIGINT NOT NULL,
	Symbol VARCHAR(10) NOT NULL,
    Name VARCHAR(30) NOT NULL
);

CREATE TABLE SZ (
    Date INTEGER NOT NULL,
    Open FLOAT NOT NULL,
    Close FLOAT NOT NULL,
    High FLOAT NOT NULL,
    Low FLOAT NOT NULL,
    Marketcap BIGINT NOT NULL,
	Symbol VARCHAR(10) NOT NULL,
    Name VARCHAR(30) NOT NULL
);

CREATE TABLE TWII (
    Date INTEGER NOT NULL,
    Open FLOAT NOT NULL,
    Close FLOAT NOT NULL,
    High FLOAT NOT NULL,
    Low FLOAT NOT NULL,
    Marketcap BIGINT NOT NULL,
	Symbol VARCHAR(10) NOT NULL,
    Name VARCHAR(30) NOT NULL
);